# Generated by Django 5.2.5 on 2025-09-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_contactsubmission_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department or office name', max_length=200)),
                ('department_type', models.CharField(choices=[('academic', 'Academic Department'), ('administrative', 'Administrative Office')], default='academic', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of the department')),
                ('office_location', models.CharField(blank=True, help_text='Office location/room', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('head_name', models.CharField(blank=True, help_text='Department head/dean name', max_length=100)),
                ('head_title', models.CharField(blank=True, help_text='Title (Dean, Director, etc.)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('position_type', models.CharField(choices=[('faculty', 'Faculty'), ('administrative', 'Administrative Staff'), ('support', 'Support Staff')], default='faculty', max_length=20)),
                ('title', models.CharField(help_text='Job title or position', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization or expertise', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or background')),
                ('qualifications', models.TextField(blank=True, help_text='Educational qualifications')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='portal.department')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['department', 'position_type', 'display_order', 'last_name', 'first_name'],
            },
        ),
    ]
