# Generated by Django 4.2.4 on 2025-10-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_department_personnel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionsImportantDate',
        ),
    ]
