# Generated by Django 5.2.5 on 2025-12-11 00:56

from django.db import migrations, models


class AddFieldIfNotExists(migrations.AddField):
    """Custom AddField that checks if column exists before adding"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if self.allow_migrate_model(schema_editor.connection.alias, model):
            # Check if column already exists (database-agnostic query)
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.COLUMNS 
                    WHERE TABLE_NAME = %s 
                    AND COLUMN_NAME = %s
                """, [model._meta.db_table, self.name])
                column_exists = cursor.fetchone()[0] > 0
                
                if not column_exists:
                    # Only add if it doesn't exist
                    super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_announcement_image'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, help_text='Achievement image', null=True, upload_to='achievements/'),
        ),
    ]
