# Generated by Django 5.2.5 on 2025-12-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_add_category_to_enrollment_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('forms-enrollment', 'Forms - Enrollment'), ('forms-clearance', 'Forms - Clearance'), ('forms-request', 'Forms - Request'), ('forms-shift-change', 'Forms - Shift/Change'), ('hr-policies', 'HR Policies'), ('hr-forms', 'HR Forms'), ('syllabi', 'Syllabi'), ('manuals', 'Manuals'), ('handbooks', 'Handbooks'), ('other', 'Other')], default='other', help_text='Download category', max_length=30)),
                ('title', models.CharField(help_text='Download title/name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the download')),
                ('file', models.FileField(help_text='File to download (PDF, DOC, etc.)', upload_to='downloads/')),
                ('file_type', models.CharField(blank=True, help_text='File type (e.g., PDF, DOCX)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this download is currently available')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['category', 'display_order', 'title'],
            },
        ),
    ]
